[package]
name = "sisprog"
version = "1.0.1"
authors = ["Adarah <lucasyharada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4.0"
clap = "2.33.1"
